### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by imns** [mailchimp/mcapi2-node-examples#6]
You really really need to develop some documentation on how to use the Node wrapper, or add to this example project with a full set of api calls, including all of the possible options that can be passed.

**Comment by toomuchpete** [comment]
Hi @imns -- the full set of API calls available in the API (and, therefore the wrapper) can be found on our [API Documentation Site](https://apidocs.mailchimp.com/). You can also check out the [actual wrapper code](https://bitbucket.org/mailchimp/mailchimp-api-node) if you want to dig a little deeper. This example is here for folks who might need a little more guidance on how to use the API with Node, but is not intended to serve as full documentation.

Thanks!

**Comment by richardpenner** [comment]
@toomuchpete your answer here would make sense if your library conformed to Node standards, which it clearly does not. The Node MailChimp wrapper is clearly built by someone that does not use Node.

The API documentation site is a good reference for knowing what's possible with MailChimp's API, but it requires a lot of mental gymnastics when translating it to Node.

You'd be better off creating a README.md based off of the documentation in ```mailchimp.js```, rather than this lame example set that does the very minimum with a couple of incomplete examples. 

I think this issue should be re-opened.

**Comment by toomuchpete** [comment]
Unfortunately that won't be possible. With v3.0 in beta, we're focusing our energies there right now. This style of example has proven to be a bad idea, so we won't be replicating them for v3.0.
